version: "3"

services:
  arrowhead-core-mysql:
    container_name: arrowhead-core-mysql
    image: mysql:8.0
    command: --host-cache-size=0 
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=arrowhead
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  arrowhead-core:
    container_name: arrowhead-core
    build: ../
    depends_on:
      - arrowhead-core-mysql
    environment:
      - JVM_FLAGS=-XX:+UseSerialGC -Xmx1G -Xms32m # Lowers memory usage of the services, but also lowers performance.
      - MYSQL_HOST=arrowhead-core-mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=arrowhead
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - SR_ADDRESS=serviceregistry.testcloud2.aitia.arrowhead.eu
      - SR_PORT=8443
      
    volumes:
      # Only systems with provided .properties files will be started when the container stars.
      - ./properties/serviceregistry.properties:/opt/arrowhead-core/serviceregistry/application.properties
      - ./properties/authorization.properties:/opt/arrowhead-core/authorization/application.properties
      - ./properties/orchestrator.properties:/opt/arrowhead-core/orchestrator/application.properties
      - ./properties/eventhandler.properties:/opt/arrowhead-core/eventhandler/application.properties
      - ./properties/gatekeeper.properties:/opt/arrowhead-core/gatekeeper/application.properties
      - ./properties/gateway.properties:/opt/arrowhead-core/gateway/application.properties
      - ./properties/certificateauthority.properties:/opt/arrowhead-core/certificate-authority/application.properties
    ports:
      - 8443:8443 # Service Registry
      - 8445:8445 # Authorization
      - 8441:8441 # Orchestrator
      - 8455:8455 # Event Handler
      - 8449:8449 # Gatekeeper
      - 8453:8453 # Gateway
      - 8448:8448 # Certificate Authority

volumes:
  mysql:
    external: true  
